"""Prompt-toolkit style for the Ness interactive terminal UI."""

from prompt_toolkit.styles import Style


# Shared true-color palette. The startup header also uses these values for its
# per-glyph logo fragments, so keep the raw colors available alongside STYLE.
GRAY = "#8a909c"
GRAY_DIM = "#5c626d"
GRAY_BRIGHT = "#c4c9d4"
CYAN = "#39c5cf"
PURPLE = "#a78bfa"
USER_BOX_BG = "#2d2d38"


STYLE = Style.from_dict(
    {
        "screen": "",
        "transcript.header": "#c4c9d4",
        "transcript.header.brand": "bold #39c5cf",
        "transcript.header.version": "#5c626d",
        "transcript.header.label": "#5c626d",
        "transcript.header.value": "#c4c9d4",
        "transcript.header.mode": "bold #87c095",
        "transcript.header.hint": "#5c626d",
        "transcript.tag.session": "bold #39c5cf",
        "transcript.tag.body": "#c4c9d4",
        "chrome.header.title": "bold #c4c9d4",
        "chrome.header.gradient": "#39c5cf",
        "chrome.header.box": "#5c626d",
        "chrome.header.key": "#8a909c",
        "chrome.header.value": "#c4c9d4",
        "chrome.header.hint": "italic #5c626d",
        "chrome.header.hint.key": "#8a909c",
        "chrome.header.hint.accent": "#a78bfa",
        "transcript.muted": "#5c626d",
        "transcript.user.label": "bold #87c095",
        "transcript.user.gutter": "#3f6f52",
        "transcript.user": f"bg:{USER_BOX_BG} #c4c9d4",
        "transcript.assistant": "",
        "transcript.assistant.streaming": "",
        "transcript.reasoning.label": "bold #2a8f97",
        "transcript.reasoning": "italic #8a909c",
        "transcript.tool": "bold #4aa3df",
        "transcript.tool.result.label": "#4aa3df",
        "transcript.tool.result": "#8a909c",
        "transcript.diff.add": "#3fb950",
        "transcript.diff.del": "#f85149",
        "transcript.diff.meta": "#2a8f97",
        "transcript.diff.hunk": "#4aa3df",
        "transcript.diff.context": "#5c626d",
        "transcript.todo.title": "bold #4aa3df",
        "transcript.todo": "#c4c9d4",
        "transcript.todo.completed": "#5c626d",
        "transcript.selection": "reverse",
        "transcript.notice.title": "bold #d29922",
        "transcript.notice": "#c4c9d4",
        "transcript.help": "#8a909c",
        "transcript.skill.title": "bold #d29922",
        "transcript.skill.name": "bold #39c5cf",
        "transcript.skill.label": "#5c626d",
        "transcript.skill.value": "#c4c9d4",
        "transcript.skill.description": "#c4c9d4",
        "transcript.skill.gutter": "#5c626d",
        "transcript.warning": "#d29922",
        "transcript.error": "bold #f85149",
        "transcript.usage": "#5c626d",
        "chrome.rule": "#a78bfa",
        "chrome.status": "#8a909c",
        "chrome.status.mode": "bold #3fb950",
        "chrome.status.busy": "bold #c6a0f6",
        "chrome.status.hint": "#5c626d",
        "chrome.queue": "bold #d29922",
        "chrome.queue.arrow": "#d29922",
        "chrome.queue.preview": "#8a909c",
        "chrome.stats": "#8a909c",
        "chrome.stats.key": "#5c626d",
        "chrome.stats.value": "#8a909c",
        "chrome.stats.accent": "#4aa3df",
        "chrome.stats.bar": "#4aa3df",
        "chrome.path": "#8a909c",
        "prompt": "bold #39c5cf",
        "prompt.mode": "bold #3fb950",
        "prompt.mode.plan": "bold #39c5cf",
        "prompt.request": "bold #d29922",
        "chrome.menu.title": "bold #39c5cf",
        "chrome.menu.row": "#8a909c",
        "chrome.menu.row.current": "bg:#1f3a63 #c4c9d4",
        "chrome.menu.arrow": "bg:#1f3a63 #39c5cf",
        "chrome.menu.label.current": "bg:#1f3a63 bold #c4c9d4",
        "chrome.menu.desc.current": "bg:#1f3a63 #8a909c",
        "chrome.menu.description": "#5c626d",
        "chrome.menu.suffix": "#39c5cf",
        "chrome.menu.checkbox": "#5c626d",
        "chrome.menu.checkbox.checked": "bold #39c5cf",
        "chrome.menu.summary": "#c4c9d4",
        "chrome.menu.scope": "bold #87c095",
        "chrome.menu.note": "#c4c9d4",
        "chrome.menu.empty": "italic #5c626d",
        "chrome.menu.detail.title": "bold #d29922",
        "chrome.menu.detail": "#8a909c",
        "chrome.menu.hint": "italic #5c626d",
        "chrome.menu.hint.key": "noitalic #39c5cf",
    }
)
